build(1).....

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,7 +1,37 @@
 
 
 #!/usr/bin/env bash
-set -e # halt script on error
+#set -e # halt script on error
 
+#bundle exec jekyll build
+#bundle exec htmlproofer ./_site
+
+
+#!/bin/bash
+
+# skip if build is triggered by pull request
+if [ $TRAVIS_PULL_REQUEST == "true" ]; then
+  echo "this is PR, exiting"
+  exit 0
+fi
+
+# enable error reporting to the console
+set -e
+
+# cleanup "_site"
+rm -rf _site
+mkdir _site
+
+# clone remote repo to "_site"
+git clone https://${0362257c6c7bdfd55ae3d134d54443c989ea43e9}@github.com/Pgahye/Pgahye.github.io.git --branch gh-pages _site
+
+# build with Jekyll into "_site"
 bundle exec jekyll build
-bundle exec htmlproofer ./_site
+
+# push
+cd _site
+git config rkgp0515@gmail.com 
+git config Pgahye 
+git add --all
+git commit -a -m "Travis $TRAVIS_BUILD_NUMBER"
+git push --force origin gh-pages
